# Generated by Django 3.1.6 on 2021-02-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
    ]
