# Generated by Django 3.1.6 on 2021-02-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_post_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default=0, upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
